apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: slinkee-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: slinkee-operator
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    ---
    logging:
      debug: {{ .Values.slinkee.logging.debug }}
      path: {{ .Values.slinkee.logging.path }}
      encoding: {{ .Values.slinkee.logging.encoding }}
    probes_api:
      listen: {{ .Values.slinkee.probes_api.listen }}
      port: {{ .Values.slinkee.probes_api.port }}
    slurm:
      slurmabler:
        image: {{ .Values.slurm.slurmabler.image }}
        service_account: {{ .Values.slurm.slurmabler.service_account }}
      munged:
        image: {{ .Values.slurm.munged.image }}
      slurmctld:
        image: {{ .Values.slurm.slurmctld.image }}
      slurmd:
        image: {{ .Values.slurm.slurmd.image }}
      slurm_toolbox:
        image: {{ .Values.slurm.slurm_toolbox.image }}
      mariadb:
        image: {{ .Values.slurm.mariadb.image }}
      slurmdbd:
        image: {{ .Values.slurm.slurmdbd.image }}
      slurmrestd:
        image: {{ .Values.slurm.slurmrestd.image }}
