---
logging:
  debug: true
  path: ./
  encoding: console
probes_api:
  listen: 127.0.0.1
  port: 9093
slurm:
  slurmabler:
    image: "ewr.vultrcr.com/slurm/slurmabler:v0.0.120"
    service_account: "slinkee"
  munged:
    image: "ewr.vultrcr.com/slurm/munged:v0.0.120"
  slurmctld:
    image: "ewr.vultrcr.com/slurm/slurmctld:v0.0.120"
  slurmd:
    image: "ewr.vultrcr.com/slurm/slurmd:v0.0.120"
  slurm_toolbox:
    image: "ewr.vultrcr.com/slurm/toolbox:v0.0.120"
  mariadb:
    image: 11.4.2-noble
  slurmdbd:
    image: "ewr.vultrcr.com/slurm/slurmdbd:v0.0.120"
  slurmrestd:
    image: "ewr.vultrcr.com/slurm/slurmrestd:v0.0.120"